server:
  port: 5435
spring:
  application:
    name: Central_Policia
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      show-sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/DB_Police
    username: postgres
    password: 123456
